import os
import json
import time
import requests
import subprocess
import re
from datetime import datetime
from pathlib import Path


class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'


ROUTER_URL = "http://localhost:20129/v1/chat/completions"
API_KEY = "sk-33c30ed152582727-i4wntx-55470e71"
MODEL_NAME = "openai/B2-Compiler-Elite"  
ROUTER_MODEL = "B2-Compiler-Elite"       
AUTHOR_NAME = "Behrad"

FALLBACK_IDEAS = [
    {
        "project_name": "DataAnalyzer_Bot", 
        "description": "یک اسکریپت پایتون که یک فایل CSV فرضی را می‌خواند و میانگین، ماکزیمم و مینیمم ستون‌های عددی را حساب می‌کند.", 
        "file_name": "analyzer.py",
        "architecture": "استفاده از کتابخانه داخلی csv و پیاده سازی توابع ماژولار."
    }
]

def extract_json(content):
    """استخراج بسیار امن JSON از متن پاسخ مدل با فیلتر کردن اضافات"""
    if not content:
        return None
    try:
        
        json_match = re.search(r'\{.*\}', content, re.DOTALL)
        if json_match:
            return json.loads(json_match.group(0))
    except json.JSONDecodeError as e:
        print(f"{Colors.RED}[❌] JSON Decode Error: {e}{Colors.ENDC}")
    return None

def generate_novel_idea():
    print(f"\n{Colors.CYAN}{Colors.BOLD}[🧠] Agent 1 (Ideation): Inventing a novel project idea...{Colors.ENDC}")
    
    headers = {
        "Authorization": f"Bearer {API_KEY}", 
        "Content-Type": "application/json"
    }
    
    
    prompt = """You are an elite autonomous AI research scientist named BehradB2.
    Propose ONE highly useful, novel, and standalone Python project. It should be a single-file script that solves a real-world problem (e.g., system utility, API wrapper, math tool).
    Return ONLY a raw JSON object (no markdown formatting, no backticks, no extra text).
    Structure EXACTLY like this:
    {
        "project_name": "CamelCaseName",
        "description": "A comprehensive 2-sentence description of what it does.",
        "file_name": "main.py",
        "architecture": "A brief explanation of how the code is structured."
    }"""
    
    payload = {
        "model": ROUTER_MODEL, 
        "messages": [{"role": "system", "content": prompt}, {"role": "user", "content": "Generate the JSON now."}], 
        "temperature": 0.8
    }
    
    try:
        response = requests.post(ROUTER_URL, headers=headers, json=payload, timeout=30)
        response.raise_for_status() 
        
        data = response.json()
        content = data['choices'][0]['message']['content']
        
        result = extract_json(content)
        if result and "project_name" in result:
            print(f"{Colors.GREEN}[✅] Idea Generated: {result['project_name']}{Colors.ENDC}")
            return result
        else:
            print(f"{Colors.YELLOW}[⚠️] Invalid JSON structure. Using Fallback Idea.{Colors.ENDC}")
            return FALLBACK_IDEAS[0]
            
    except Exception as e:
        print(f"{Colors.RED}[❌] Connection/API Error: {e}. Using Fallback Idea.{Colors.ENDC}")
        return FALLBACK_IDEAS[0]

def execute_aider_autonomously(idea, project_path):
    print(f"{Colors.BLUE}{Colors.BOLD}[⚙️] Agent 2 (Coder): Writing code via Aider...{Colors.ENDC}")
    
    
    subprocess.run(["git", "init"], cwd=project_path, capture_output=True)
    
    
    coding_prompt = (
        f"Create a file named '{idea['file_name']}'. "
        f"Write complete, production-ready Python code for this project: {idea['project_name']}. "
        f"Description: {idea['description']}. "
        f"Architecture: {idea['architecture']}. "
        f"Include thorough comments and error handling. "
        f"Add a header at the top of the file: '# Author: {AUTHOR_NAME} - Generated by BehradB2'."
    )
    
    
    aider_command = [
        "aider",
        "--openai-api-base", "http://localhost:20129/v1",
        "--openai-api-key", API_KEY,
        "--model", MODEL_NAME,
        "--yes-always",                 
        "--no-show-model-warnings",    
        "--message", coding_prompt
    ]
    
   
    try:
        result = subprocess.run(aider_command, cwd=project_path)
        return result.returncode == 0
    except Exception as e:
        print(f"{Colors.RED}[❌] Aider Execution Error: {e}{Colors.ENDC}")
        return False

def create_documentation(idea, project_path):
    print(f"{Colors.YELLOW}[📝] Agent 3 (DocWriter): Generating Official README & Metadata...{Colors.ENDC}")
    
    
    readme_content = f"""# 🚀 {idea['project_name']}

## 📖 Overview
{idea['description']}

## 🏗️ Architecture
{idea['architecture']}

---
* **Author:** {AUTHOR_NAME}
* **Generated via:** BehradB2 Autonomous Compiler System
* **Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""
    with open(project_path / "README.md", "w", encoding="utf-8") as f:
        f.write(readme_content)

    
    metadata = {
        "project_name": idea['project_name'],
        "author": AUTHOR_NAME,
        "timestamp": datetime.now().isoformat(),
        "ai_model_used": ROUTER_MODEL,
        "raw_idea": idea
    }
    with open(project_path / "run_metadata.json", "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=4, ensure_ascii=False)

def start_autonomous_loop(cycles=1):
    os.system('cls' if os.name == 'nt' else 'clear')
    print(f"{Colors.HEADER}{Colors.BOLD}")
    print("==================================================================")
    print(" 🌐 BEHRADB2 AUTONOMOUS RESEARCH SCIENTIST IS ONLINE")
    print(" 🤖 MODE: Fully Autonomous (No human intervention required)")
    print("==================================================================")
    print(f"{Colors.ENDC}")
    
    base_dir = Path("Projects_BehradB2").resolve() 
    base_dir.mkdir(exist_ok=True)
    
    for i in range(cycles):
        print(f"\n{Colors.HEADER}--- Starting Research Cycle {i+1} of {cycles} ---{Colors.ENDC}")
        
        idea = generate_novel_idea()
        if not idea: 
            print(f"{Colors.RED}[❌] Skipping cycle due to Ideation failure.{Colors.ENDC}")
            continue
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        folder_name = f"{idea['project_name']}_{timestamp}"
        project_path = base_dir / folder_name
        project_path.mkdir(parents=True, exist_ok=True)
        

        if execute_aider_autonomously(idea, project_path):
            create_documentation(idea, project_path)
            print(f"\n{Colors.GREEN}{Colors.BOLD}🎉 [SUCCESS] Project '{idea['project_name']}' completed perfectly!{Colors.ENDC}")
            print(f"{Colors.GREEN}📂 Saved in: {project_path}{Colors.ENDC}")
        else:
            print(f"\n{Colors.RED}💥 [FAILED] Project '{idea['project_name']}' encountered an error.{Colors.ENDC}")
        
        
        if i < cycles - 1:
            print(f"\n{Colors.YELLOW}⏳ Cooling down for 5 seconds before next cycle...{Colors.ENDC}")
            time.sleep(5)

if __name__ == "__main__":
    
    start_autonomous_loop(cycles=1)
